services:
  - type: web
    name: mailing-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CONNECTION_STRING
        sync: false
